DROP DATABASE IF EXISTS `twitter`;
CREATE DATABASE `twitter`;
USE `twitter`;

CREATE TABLE IF NOT EXISTS name (
 ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 NAME VARCHAR(50) NOT NULL
) ENGINE=INNODB; -- data from Python

CREATE TABLE IF NOT EXISTS tweet (
 ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 TWEET VARCHAR(1000) NOT NULL
) ENGINE=INNODB; -- data from Python

CREATE TABLE IF NOT EXISTS frequency (
 ID_WORD INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 WORD VARCHAR(50) NOT NULL,
 COUNT INT NOT NULL
) ENGINE=INNODB; -- data from Python

CREATE TABLE IF NOT EXISTS length (
 ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 LENGTH INT NOT NULL
) ENGINE=INNODB; -- data from Python

-- create local_host Jaroslav_Kotrba for R connection
CREATE USER 'Jaroslav_Kotrba'@'localhost' IDENTIFIED BY 'milites';
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE, SHOW VIEW ON twitter.* TO 'Jaroslav_Kotrba'@'localhost';
